name: CLI CI

on:
  push:
    branches:
      - "**"  
  pull_request:
    branches:
    - main  

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13.3"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest gmail_integration/tests/
